// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: internal_ops.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const deleteAdminEvent = `-- name: DeleteAdminEvent :exec
DELETE FROM admin_events WHERE id = $1
`

func (q *Queries) DeleteAdminEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAdminEvent, id)
	return err
}

const deleteFinanceOp = `-- name: DeleteFinanceOp :exec
DELETE FROM finance_ops WHERE id = $1
`

func (q *Queries) DeleteFinanceOp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFinanceOp, id)
	return err
}

const deleteITAsset = `-- name: DeleteITAsset :exec
DELETE FROM it_assets WHERE id = $1
`

func (q *Queries) DeleteITAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteITAsset, id)
	return err
}

const deleteLegalOp = `-- name: DeleteLegalOp :exec
DELETE FROM legal_ops WHERE id = $1
`

func (q *Queries) DeleteLegalOp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLegalOp, id)
	return err
}

const deletePeopleOp = `-- name: DeletePeopleOp :exec
DELETE FROM people_ops WHERE id = $1
`

func (q *Queries) DeletePeopleOp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePeopleOp, id)
	return err
}

const getAdminEventByID = `-- name: GetAdminEventByID :one
SELECT id, founder_id, event_type, title, payload, meeting_date, action_items, sop_reference, created_at, updated_at FROM admin_events
WHERE id = $1
`

func (q *Queries) GetAdminEventByID(ctx context.Context, id uuid.UUID) (AdminEvent, error) {
	row := q.db.QueryRowContext(ctx, getAdminEventByID, id)
	var i AdminEvent
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.Title,
		&i.Payload,
		&i.MeetingDate,
		&i.ActionItems,
		&i.SopReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinanceOpByID = `-- name: GetFinanceOpByID :one
SELECT id, founder_id, task_type, payload, status, due_date, completed_at, created_at, updated_at FROM finance_ops
WHERE id = $1
`

func (q *Queries) GetFinanceOpByID(ctx context.Context, id uuid.UUID) (FinanceOp, error) {
	row := q.db.QueryRowContext(ctx, getFinanceOpByID, id)
	var i FinanceOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.TaskType,
		&i.Payload,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getITAssetByID = `-- name: GetITAssetByID :one
SELECT id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at FROM it_assets
WHERE id = $1
`

func (q *Queries) GetITAssetByID(ctx context.Context, id uuid.UUID) (ItAsset, error) {
	row := q.db.QueryRowContext(ctx, getITAssetByID, id)
	var i ItAsset
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.AssetType,
		&i.AssetName,
		&i.MonthlyCost,
		&i.LastUsedDate,
		&i.RenewalDate,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLegalOpByID = `-- name: GetLegalOpByID :one
SELECT id, founder_id, document_type, document_name, expiry_date, esign_status, payload, status, created_at, updated_at FROM legal_ops
WHERE id = $1
`

func (q *Queries) GetLegalOpByID(ctx context.Context, id uuid.UUID) (LegalOp, error) {
	row := q.db.QueryRowContext(ctx, getLegalOpByID, id)
	var i LegalOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.DocumentType,
		&i.DocumentName,
		&i.ExpiryDate,
		&i.EsignStatus,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeopleOpByID = `-- name: GetPeopleOpByID :one
SELECT id, founder_id, event_type, employee_name, payload, status, event_date, completed_at, created_at, updated_at FROM people_ops
WHERE id = $1
`

func (q *Queries) GetPeopleOpByID(ctx context.Context, id uuid.UUID) (PeopleOp, error) {
	row := q.db.QueryRowContext(ctx, getPeopleOpByID, id)
	var i PeopleOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.EmployeeName,
		&i.Payload,
		&i.Status,
		&i.EventDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminEvent = `-- name: InsertAdminEvent :one
INSERT INTO admin_events (founder_id, event_type, title, payload, meeting_date, action_items, sop_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, founder_id, event_type, title, payload, meeting_date, action_items, sop_reference, created_at, updated_at
`

type InsertAdminEventParams struct {
	FounderID    uuid.NullUUID         `json:"founder_id"`
	EventType    string                `json:"event_type"`
	Title        sql.NullString        `json:"title"`
	Payload      json.RawMessage       `json:"payload"`
	MeetingDate  sql.NullTime          `json:"meeting_date"`
	ActionItems  pqtype.NullRawMessage `json:"action_items"`
	SopReference sql.NullString        `json:"sop_reference"`
}

func (q *Queries) InsertAdminEvent(ctx context.Context, arg InsertAdminEventParams) (AdminEvent, error) {
	row := q.db.QueryRowContext(ctx, insertAdminEvent,
		arg.FounderID,
		arg.EventType,
		arg.Title,
		arg.Payload,
		arg.MeetingDate,
		arg.ActionItems,
		arg.SopReference,
	)
	var i AdminEvent
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.Title,
		&i.Payload,
		&i.MeetingDate,
		&i.ActionItems,
		&i.SopReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFinanceOp = `-- name: InsertFinanceOp :one
INSERT INTO finance_ops (founder_id, task_type, payload, status, due_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, founder_id, task_type, payload, status, due_date, completed_at, created_at, updated_at
`

type InsertFinanceOpParams struct {
	FounderID uuid.NullUUID   `json:"founder_id"`
	TaskType  string          `json:"task_type"`
	Payload   json.RawMessage `json:"payload"`
	Status    sql.NullString  `json:"status"`
	DueDate   sql.NullTime    `json:"due_date"`
}

func (q *Queries) InsertFinanceOp(ctx context.Context, arg InsertFinanceOpParams) (FinanceOp, error) {
	row := q.db.QueryRowContext(ctx, insertFinanceOp,
		arg.FounderID,
		arg.TaskType,
		arg.Payload,
		arg.Status,
		arg.DueDate,
	)
	var i FinanceOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.TaskType,
		&i.Payload,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertITAsset = `-- name: InsertITAsset :one
INSERT INTO it_assets (founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at
`

type InsertITAssetParams struct {
	FounderID    uuid.NullUUID   `json:"founder_id"`
	AssetType    string          `json:"asset_type"`
	AssetName    string          `json:"asset_name"`
	MonthlyCost  sql.NullString  `json:"monthly_cost"`
	LastUsedDate sql.NullTime    `json:"last_used_date"`
	RenewalDate  sql.NullTime    `json:"renewal_date"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
}

func (q *Queries) InsertITAsset(ctx context.Context, arg InsertITAssetParams) (ItAsset, error) {
	row := q.db.QueryRowContext(ctx, insertITAsset,
		arg.FounderID,
		arg.AssetType,
		arg.AssetName,
		arg.MonthlyCost,
		arg.LastUsedDate,
		arg.RenewalDate,
		arg.Payload,
		arg.Status,
	)
	var i ItAsset
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.AssetType,
		&i.AssetName,
		&i.MonthlyCost,
		&i.LastUsedDate,
		&i.RenewalDate,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLegalOp = `-- name: InsertLegalOp :one
INSERT INTO legal_ops (founder_id, document_type, document_name, expiry_date, esign_status, payload, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, founder_id, document_type, document_name, expiry_date, esign_status, payload, status, created_at, updated_at
`

type InsertLegalOpParams struct {
	FounderID    uuid.NullUUID   `json:"founder_id"`
	DocumentType string          `json:"document_type"`
	DocumentName sql.NullString  `json:"document_name"`
	ExpiryDate   sql.NullTime    `json:"expiry_date"`
	EsignStatus  sql.NullString  `json:"esign_status"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
}

func (q *Queries) InsertLegalOp(ctx context.Context, arg InsertLegalOpParams) (LegalOp, error) {
	row := q.db.QueryRowContext(ctx, insertLegalOp,
		arg.FounderID,
		arg.DocumentType,
		arg.DocumentName,
		arg.ExpiryDate,
		arg.EsignStatus,
		arg.Payload,
		arg.Status,
	)
	var i LegalOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.DocumentType,
		&i.DocumentName,
		&i.ExpiryDate,
		&i.EsignStatus,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPeopleOp = `-- name: InsertPeopleOp :one
INSERT INTO people_ops (founder_id, event_type, employee_name, payload, status, event_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, founder_id, event_type, employee_name, payload, status, event_date, completed_at, created_at, updated_at
`

type InsertPeopleOpParams struct {
	FounderID    uuid.NullUUID   `json:"founder_id"`
	EventType    string          `json:"event_type"`
	EmployeeName sql.NullString  `json:"employee_name"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
	EventDate    sql.NullTime    `json:"event_date"`
}

func (q *Queries) InsertPeopleOp(ctx context.Context, arg InsertPeopleOpParams) (PeopleOp, error) {
	row := q.db.QueryRowContext(ctx, insertPeopleOp,
		arg.FounderID,
		arg.EventType,
		arg.EmployeeName,
		arg.Payload,
		arg.Status,
		arg.EventDate,
	)
	var i PeopleOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.EmployeeName,
		&i.Payload,
		&i.Status,
		&i.EventDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEventsByFounder = `-- name: ListAdminEventsByFounder :many
SELECT id, founder_id, event_type, title, payload, meeting_date, action_items, sop_reference, created_at, updated_at FROM admin_events
WHERE founder_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdminEventsByFounder(ctx context.Context, founderID uuid.NullUUID) ([]AdminEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAdminEventsByFounder, founderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminEvent{}
	for rows.Next() {
		var i AdminEvent
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.EventType,
			&i.Title,
			&i.Payload,
			&i.MeetingDate,
			&i.ActionItems,
			&i.SopReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminEventsByType = `-- name: ListAdminEventsByType :many
SELECT id, founder_id, event_type, title, payload, meeting_date, action_items, sop_reference, created_at, updated_at FROM admin_events
WHERE event_type = $1
ORDER BY meeting_date DESC
`

func (q *Queries) ListAdminEventsByType(ctx context.Context, eventType string) ([]AdminEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAdminEventsByType, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminEvent{}
	for rows.Next() {
		var i AdminEvent
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.EventType,
			&i.Title,
			&i.Payload,
			&i.MeetingDate,
			&i.ActionItems,
			&i.SopReference,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceOpsByFounder = `-- name: ListFinanceOpsByFounder :many
SELECT id, founder_id, task_type, payload, status, due_date, completed_at, created_at, updated_at FROM finance_ops
WHERE founder_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFinanceOpsByFounder(ctx context.Context, founderID uuid.NullUUID) ([]FinanceOp, error) {
	rows, err := q.db.QueryContext(ctx, listFinanceOpsByFounder, founderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceOp{}
	for rows.Next() {
		var i FinanceOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.TaskType,
			&i.Payload,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinanceOpsByStatus = `-- name: ListFinanceOpsByStatus :many
SELECT id, founder_id, task_type, payload, status, due_date, completed_at, created_at, updated_at FROM finance_ops
WHERE status = $1
ORDER BY due_date ASC
`

func (q *Queries) ListFinanceOpsByStatus(ctx context.Context, status sql.NullString) ([]FinanceOp, error) {
	rows, err := q.db.QueryContext(ctx, listFinanceOpsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceOp{}
	for rows.Next() {
		var i FinanceOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.TaskType,
			&i.Payload,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listITAssetsByFounder = `-- name: ListITAssetsByFounder :many
SELECT id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at FROM it_assets
WHERE founder_id = $1
ORDER BY monthly_cost DESC
`

func (q *Queries) ListITAssetsByFounder(ctx context.Context, founderID uuid.NullUUID) ([]ItAsset, error) {
	rows, err := q.db.QueryContext(ctx, listITAssetsByFounder, founderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItAsset{}
	for rows.Next() {
		var i ItAsset
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.AssetType,
			&i.AssetName,
			&i.MonthlyCost,
			&i.LastUsedDate,
			&i.RenewalDate,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listITAssetsByStatus = `-- name: ListITAssetsByStatus :many
SELECT id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at FROM it_assets
WHERE status = $1
ORDER BY asset_name ASC
`

func (q *Queries) ListITAssetsByStatus(ctx context.Context, status sql.NullString) ([]ItAsset, error) {
	rows, err := q.db.QueryContext(ctx, listITAssetsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItAsset{}
	for rows.Next() {
		var i ItAsset
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.AssetType,
			&i.AssetName,
			&i.MonthlyCost,
			&i.LastUsedDate,
			&i.RenewalDate,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listITAssetsRenewingSoon = `-- name: ListITAssetsRenewingSoon :many
SELECT id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at FROM it_assets
WHERE renewal_date IS NOT NULL
  AND renewal_date <= NOW() + INTERVAL '30 days'
  AND status = 'active'
ORDER BY renewal_date ASC
`

func (q *Queries) ListITAssetsRenewingSoon(ctx context.Context) ([]ItAsset, error) {
	rows, err := q.db.QueryContext(ctx, listITAssetsRenewingSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItAsset{}
	for rows.Next() {
		var i ItAsset
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.AssetType,
			&i.AssetName,
			&i.MonthlyCost,
			&i.LastUsedDate,
			&i.RenewalDate,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalOpsByFounder = `-- name: ListLegalOpsByFounder :many
SELECT id, founder_id, document_type, document_name, expiry_date, esign_status, payload, status, created_at, updated_at FROM legal_ops
WHERE founder_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLegalOpsByFounder(ctx context.Context, founderID uuid.NullUUID) ([]LegalOp, error) {
	rows, err := q.db.QueryContext(ctx, listLegalOpsByFounder, founderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalOp{}
	for rows.Next() {
		var i LegalOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.DocumentType,
			&i.DocumentName,
			&i.ExpiryDate,
			&i.EsignStatus,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegalOpsExpiringSoon = `-- name: ListLegalOpsExpiringSoon :many
SELECT id, founder_id, document_type, document_name, expiry_date, esign_status, payload, status, created_at, updated_at FROM legal_ops
WHERE expiry_date IS NOT NULL
  AND expiry_date <= NOW() + INTERVAL '30 days'
  AND esign_status IS DISTINCT FROM 'expired'
ORDER BY expiry_date ASC
`

func (q *Queries) ListLegalOpsExpiringSoon(ctx context.Context) ([]LegalOp, error) {
	rows, err := q.db.QueryContext(ctx, listLegalOpsExpiringSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegalOp{}
	for rows.Next() {
		var i LegalOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.DocumentType,
			&i.DocumentName,
			&i.ExpiryDate,
			&i.EsignStatus,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleOpsByEventType = `-- name: ListPeopleOpsByEventType :many
SELECT id, founder_id, event_type, employee_name, payload, status, event_date, completed_at, created_at, updated_at FROM people_ops
WHERE event_type = $1
ORDER BY event_date DESC
`

func (q *Queries) ListPeopleOpsByEventType(ctx context.Context, eventType string) ([]PeopleOp, error) {
	rows, err := q.db.QueryContext(ctx, listPeopleOpsByEventType, eventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeopleOp{}
	for rows.Next() {
		var i PeopleOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.EventType,
			&i.EmployeeName,
			&i.Payload,
			&i.Status,
			&i.EventDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleOpsByFounder = `-- name: ListPeopleOpsByFounder :many
SELECT id, founder_id, event_type, employee_name, payload, status, event_date, completed_at, created_at, updated_at FROM people_ops
WHERE founder_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPeopleOpsByFounder(ctx context.Context, founderID uuid.NullUUID) ([]PeopleOp, error) {
	rows, err := q.db.QueryContext(ctx, listPeopleOpsByFounder, founderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeopleOp{}
	for rows.Next() {
		var i PeopleOp
		if err := rows.Scan(
			&i.ID,
			&i.FounderID,
			&i.EventType,
			&i.EmployeeName,
			&i.Payload,
			&i.Status,
			&i.EventDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminEvent = `-- name: UpdateAdminEvent :one
UPDATE admin_events
SET title = COALESCE($2, title),
    payload = COALESCE($3, payload),
    meeting_date = COALESCE($4, meeting_date),
    action_items = COALESCE($5, action_items),
    sop_reference = COALESCE($6, sop_reference),
    updated_at = NOW()
WHERE id = $1
RETURNING id, founder_id, event_type, title, payload, meeting_date, action_items, sop_reference, created_at, updated_at
`

type UpdateAdminEventParams struct {
	ID           uuid.UUID             `json:"id"`
	Title        sql.NullString        `json:"title"`
	Payload      json.RawMessage       `json:"payload"`
	MeetingDate  sql.NullTime          `json:"meeting_date"`
	ActionItems  pqtype.NullRawMessage `json:"action_items"`
	SopReference sql.NullString        `json:"sop_reference"`
}

func (q *Queries) UpdateAdminEvent(ctx context.Context, arg UpdateAdminEventParams) (AdminEvent, error) {
	row := q.db.QueryRowContext(ctx, updateAdminEvent,
		arg.ID,
		arg.Title,
		arg.Payload,
		arg.MeetingDate,
		arg.ActionItems,
		arg.SopReference,
	)
	var i AdminEvent
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.Title,
		&i.Payload,
		&i.MeetingDate,
		&i.ActionItems,
		&i.SopReference,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFinanceOpStatus = `-- name: UpdateFinanceOpStatus :one
UPDATE finance_ops
SET status = $2,
    completed_at = CASE 
        WHEN $2 IN ('completed', 'auto_executed') AND completed_at IS NULL THEN NOW()
        WHEN $2 NOT IN ('completed', 'auto_executed') THEN NULL
        ELSE completed_at
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, founder_id, task_type, payload, status, due_date, completed_at, created_at, updated_at
`

type UpdateFinanceOpStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdateFinanceOpStatus(ctx context.Context, arg UpdateFinanceOpStatusParams) (FinanceOp, error) {
	row := q.db.QueryRowContext(ctx, updateFinanceOpStatus, arg.ID, arg.Status)
	var i FinanceOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.TaskType,
		&i.Payload,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateITAssetStatus = `-- name: UpdateITAssetStatus :one
UPDATE it_assets
SET status = $2,
    last_used_date = COALESCE($3, last_used_date),
    updated_at = NOW()
WHERE id = $1
RETURNING id, founder_id, asset_type, asset_name, monthly_cost, last_used_date, renewal_date, payload, status, created_at, updated_at
`

type UpdateITAssetStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       sql.NullString `json:"status"`
	LastUsedDate sql.NullTime   `json:"last_used_date"`
}

func (q *Queries) UpdateITAssetStatus(ctx context.Context, arg UpdateITAssetStatusParams) (ItAsset, error) {
	row := q.db.QueryRowContext(ctx, updateITAssetStatus, arg.ID, arg.Status, arg.LastUsedDate)
	var i ItAsset
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.AssetType,
		&i.AssetName,
		&i.MonthlyCost,
		&i.LastUsedDate,
		&i.RenewalDate,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLegalOpStatus = `-- name: UpdateLegalOpStatus :one
UPDATE legal_ops
SET status = $2,
    esign_status = COALESCE($3, esign_status),
    updated_at = NOW()
WHERE id = $1
RETURNING id, founder_id, document_type, document_name, expiry_date, esign_status, payload, status, created_at, updated_at
`

type UpdateLegalOpStatusParams struct {
	ID          uuid.UUID      `json:"id"`
	Status      sql.NullString `json:"status"`
	EsignStatus sql.NullString `json:"esign_status"`
}

func (q *Queries) UpdateLegalOpStatus(ctx context.Context, arg UpdateLegalOpStatusParams) (LegalOp, error) {
	row := q.db.QueryRowContext(ctx, updateLegalOpStatus, arg.ID, arg.Status, arg.EsignStatus)
	var i LegalOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.DocumentType,
		&i.DocumentName,
		&i.ExpiryDate,
		&i.EsignStatus,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePeopleOpStatus = `-- name: UpdatePeopleOpStatus :one
UPDATE people_ops
SET status = $2,
    completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, founder_id, event_type, employee_name, payload, status, event_date, completed_at, created_at, updated_at
`

type UpdatePeopleOpStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) UpdatePeopleOpStatus(ctx context.Context, arg UpdatePeopleOpStatusParams) (PeopleOp, error) {
	row := q.db.QueryRowContext(ctx, updatePeopleOpStatus, arg.ID, arg.Status)
	var i PeopleOp
	err := row.Scan(
		&i.ID,
		&i.FounderID,
		&i.EventType,
		&i.EmployeeName,
		&i.Payload,
		&i.Status,
		&i.EventDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
