// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
	"json"
)

type AdminEvent struct {
	ID           uuid.UUID             `json:"id"`
	FounderID    uuid.NullUUID         `json:"founder_id"`
	EventType    string                `json:"event_type"`
	Title        sql.NullString        `json:"title"`
	Payload      json.RawMessage       `json:"payload"`
	MeetingDate  sql.NullTime          `json:"meeting_date"`
	ActionItems  pqtype.NullRawMessage `json:"action_items"`
	SopReference sql.NullString        `json:"sop_reference"`
	CreatedAt    sql.NullTime          `json:"created_at"`
	UpdatedAt    sql.NullTime          `json:"updated_at"`
}

type Commitment struct {
	ID              uuid.UUID      `json:"id"`
	FounderID       uuid.NullUUID  `json:"founder_id"`
	Description     string         `json:"description"`
	CommittedAt     sql.NullTime   `json:"committed_at"`
	DueBy           sql.NullTime   `json:"due_by"`
	Completed       sql.NullBool   `json:"completed"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	SourceTriggerID uuid.NullUUID  `json:"source_trigger_id"`
	Category        sql.NullString `json:"category"`
}

type CompanyContext struct {
	ID            uuid.UUID       `json:"id"`
	FounderID     uuid.NullUUID   `json:"founder_id"`
	ContextType   string          `json:"context_type"`
	Content       string          `json:"content"`
	Source        string          `json:"source"`
	CapturedFrom  sql.NullString  `json:"captured_from"`
	Confidence    sql.NullFloat64 `json:"confidence"`
	ValidUntil    sql.NullTime    `json:"valid_until"`
	QdrantPointID sql.NullString  `json:"qdrant_point_id"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type FinanceOp struct {
	ID          uuid.UUID       `json:"id"`
	FounderID   uuid.NullUUID   `json:"founder_id"`
	TaskType    string          `json:"task_type"`
	Payload     json.RawMessage `json:"payload"`
	Status      sql.NullString  `json:"status"`
	DueDate     sql.NullTime    `json:"due_date"`
	CompletedAt sql.NullTime    `json:"completed_at"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type Founder struct {
	ID                 uuid.UUID      `json:"id"`
	SlackUserID        string         `json:"slack_user_id"`
	SlackTeamID        string         `json:"slack_team_id"`
	Name               string         `json:"name"`
	Email              sql.NullString `json:"email"`
	Archetype          sql.NullString `json:"archetype"`
	Stage              sql.NullString `json:"stage"`
	OnboardingComplete sql.NullBool   `json:"onboarding_complete"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type ItAsset struct {
	ID           uuid.UUID       `json:"id"`
	FounderID    uuid.NullUUID   `json:"founder_id"`
	AssetType    string          `json:"asset_type"`
	AssetName    string          `json:"asset_name"`
	MonthlyCost  sql.NullString  `json:"monthly_cost"`
	LastUsedDate sql.NullTime    `json:"last_used_date"`
	RenewalDate  sql.NullTime    `json:"renewal_date"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type LegalOp struct {
	ID           uuid.UUID       `json:"id"`
	FounderID    uuid.NullUUID   `json:"founder_id"`
	DocumentType string          `json:"document_type"`
	DocumentName sql.NullString  `json:"document_name"`
	ExpiryDate   sql.NullTime    `json:"expiry_date"`
	EsignStatus  sql.NullString  `json:"esign_status"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type MemorySnapshot struct {
	ID                       uuid.UUID             `json:"id"`
	FounderID                uuid.NullUUID         `json:"founder_id"`
	SnapshotType             string                `json:"snapshot_type"`
	CommitmentCompletionRate sql.NullFloat64       `json:"commitment_completion_rate"`
	CustomerCallFrequency    sql.NullFloat64       `json:"customer_call_frequency"`
	CodingVsCustomerRatio    sql.NullFloat64       `json:"coding_vs_customer_ratio"`
	DecisionStallAvgDays     sql.NullFloat64       `json:"decision_stall_avg_days"`
	MomentumScore            sql.NullFloat64       `json:"momentum_score"`
	DominantArchetype        sql.NullString        `json:"dominant_archetype"`
	DetectedPatterns         pqtype.NullRawMessage `json:"detected_patterns"`
	CreatedAt                sql.NullTime          `json:"created_at"`
}

type PeopleOp struct {
	ID           uuid.UUID       `json:"id"`
	FounderID    uuid.NullUUID   `json:"founder_id"`
	EventType    string          `json:"event_type"`
	EmployeeName sql.NullString  `json:"employee_name"`
	Payload      json.RawMessage `json:"payload"`
	Status       sql.NullString  `json:"status"`
	EventDate    sql.NullTime    `json:"event_date"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
}

type TriggerLog struct {
	ID                uuid.UUID             `json:"id"`
	FounderID         uuid.NullUUID         `json:"founder_id"`
	TriggerType       string                `json:"trigger_type"`
	Score             float64               `json:"score"`
	ThresholdUsed     float64               `json:"threshold_used"`
	Fired             bool                  `json:"fired"`
	SuppressionReason sql.NullString        `json:"suppression_reason"`
	SignalPayload     pqtype.NullRawMessage `json:"signal_payload"`
	MessageSent       sql.NullString        `json:"message_sent"`
	SlackMessageTs    sql.NullString        `json:"slack_message_ts"`
	FounderFeedback   sql.NullString        `json:"founder_feedback"`
	CreatedAt         sql.NullTime          `json:"created_at"`
}

type WeeklyReflection struct {
	ID          uuid.UUID      `json:"id"`
	FounderID   uuid.NullUUID  `json:"founder_id"`
	WeekNumber  int32          `json:"week_number"`
	Year        int32          `json:"year"`
	Q1Done      sql.NullString `json:"q1_done"`
	Q2Avoided   sql.NullString `json:"q2_avoided"`
	Q3Decision  sql.NullString `json:"q3_decision"`
	Q4Customer  sql.NullString `json:"q4_customer"`
	Q5Emotion   sql.NullString `json:"q5_emotion"`
	RawText     sql.NullString `json:"raw_text"`
	SubmittedAt sql.NullTime   `json:"submitted_at"`
}
