"""
BI Agent State for Sarthi v1.0.

Defines the TypedDict state machine for the BI Agent LangGraph.
No external imports needed — pure Python typing.
"""
from typing import TypedDict


class BIState(TypedDict):
    """
    State machine for BI Agent.

    Fields:
        tenant_id:         Tenant identifier for multi-tenant isolation
        query:             Natural language question from founder
        query_type:        ADHOC | SCHEDULED | TRIGGERED
        query_category:    trend | breakdown | comparison | aggregation
        data_sources:      List of available tables
        generated_sql:     SQL generated by LLM
        sql_result:        Dict with rows, columns, count
        chart_type:        line | bar | pie | none
        chart_path:        PNG absolute path or ""
        past_queries:      List of past queries from Qdrant bi_memory
        narrative:         LLM plain English explanation
        output_message:    Formatted Telegram message
        error:             Last error string, "" if none
        retry_count:       SQL retries so far (max 2)
        langfuse_trace_id: Langfuse trace ID for observability
    """
    tenant_id:         str
    query:             str
    query_type:        str
    query_category:    str
    data_sources:      list
    generated_sql:     str
    sql_result:        dict
    chart_type:        str
    chart_path:        str
    past_queries:      list
    narrative:         str
    output_message:    str
    error:             str
    retry_count:       int
    langfuse_trace_id: str
